In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pp

In [2]:
epz = pd.read_csv('/content/empz_01.csv')

In [3]:
epz.columns

Index(['EmployeeID', 'JobInvolvement', 'PerformanceRating',
       'EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance', 'Age',
       'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'Gender', 'JobLevel',
       'JobRole', 'MaritalStatus', 'MonthlyIncome', 'NumCompaniesWorked',
       'Over18', 'PercentSalaryHike', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [4]:
x = epz[['StandardHours','DistanceFromHome']]

In [5]:
x.head()

StandardHours  DistanceFromHome
0              8                 6
1              8                10
2              8                17
3              8                 2
4              8                10

In [6]:
from sklearn.linear_model import LinearRegression
mod = LinearRegression()

In [7]:
y = epz[['YearsAtCompany']]

In [ ]:
mod.fit(x,y)

In [9]:
mod.coef_

array([[0.        , 0.02394429]])

In [10]:
mod.intercept_

array([6.78805498])

In [11]:
yr = mod.predict([[8,12]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [12]:
print(yr)

[[7.07538645]]


In [15]:
from sklearn.model_selection import train_test_split


In [17]:
X_train , X_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
print(y_test)

      YearsAtCompany
1567               8
683                9
117                5
1581               2
3861              11
...              ...
3537              14
134                4
3056               7
2962               5
4399              11

[882 rows x 1 columns]


In [19]:
mod.fit(X_train,y_train)

LinearRegression()

In [20]:
p_y = mod.predict(X_test)

In [21]:
print(p_y)

[[7.41412766]
 [6.94922309]
 [6.77794246]
 [6.7534738 ]
 [6.97369176]
 [7.02262908]
 [6.87581711]
 [6.77794246]
 [6.99816042]
 [6.80241113]
 [7.19390971]
 [6.99816042]
 [6.85134845]
 [7.16944105]
 [7.19390971]
 [6.97369176]
 [6.85134845]
 [6.80241113]
 [7.09603506]
 [6.77794246]
 [6.82687979]
 [7.12050372]
 [7.36519034]
 [7.29178435]
 [6.97369176]
 [6.7534738 ]
 [6.77794246]
 [6.92475443]
 [7.389659  ]
 [7.43859632]
 [6.85134845]
 [6.82687979]
 [7.09603506]
 [6.77794246]
 [6.80241113]
 [6.94922309]
 [7.16944105]
 [6.90028577]
 [6.7534738 ]
 [6.97369176]
 [6.77794246]
 [7.14497239]
 [7.0715664 ]
 [6.7534738 ]
 [6.80241113]
 [7.36519034]
 [6.77794246]
 [6.7534738 ]
 [6.7534738 ]
 [6.99816042]
 [7.19390971]
 [6.94922309]
 [6.7534738 ]
 [7.31625302]
 [6.94922309]
 [6.82687979]
 [6.97369176]
 [6.77794246]
 [6.82687979]
 [6.80241113]
 [7.41412766]
 [6.7534738 ]
 [6.7534738 ]
 [6.7534738 ]
 [6.77794246]
 [6.7534738 ]
 [6.77794246]
 [7.12050372]
 [6.80241113]
 [6.97369176]
 [7.34072168]
 [7.07

In [22]:
from sklearn import metrics

In [23]:
print(np.sqrt(metrics.mean_squared_error(y_test,p_y)))

6.025811007521459
